# Generated by Django 3.2.9 on 2022-04-10 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juanzeng', '0001_initial'),
        ('juanji', '0001_initial'),
        ('wupinleibie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chuli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biaoti', models.CharField(default='', max_length=255, verbose_name='标题')),
                ('bianhao', models.CharField(default='', max_length=50, verbose_name='编号')),
                ('wupin', models.CharField(default='', max_length=255, verbose_name='物品')),
                ('shuliang', models.IntegerField(default=0, verbose_name='数量')),
                ('juanzengren', models.CharField(db_column='juanzengren', default='', max_length=50, verbose_name='捐赠人')),
                ('leixing', models.CharField(choices=[('回收处理', '回收处理'), ('退还处理', '退还处理')], default='', max_length=512, verbose_name='类型')),
                ('beizhuxinxi', models.TextField(default='', verbose_name='备注信息')),
                ('tianjiaren', models.CharField(db_column='tianjiaren', default='', max_length=50, verbose_name='添加人')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('juanjiid', models.ForeignKey(db_column='juanjiid', default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='chuli_Juanji_juanjiid', to='juanji.juanji', verbose_name='捐寄id')),
                ('juanzengid', models.ForeignKey(db_column='juanzengid', default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='chuli_Juanzeng_juanzengid', to='juanzeng.juanzeng', verbose_name='捐赠id')),
                ('wupinleibie', models.ForeignKey(db_column='wupinleibie', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chuli_Wupinleibie_wupinleibie', to='wupinleibie.wupinleibie')),
            ],
            options={
                'verbose_name': '处理',
                'verbose_name_plural': '处理',
                'db_table': 'chuli',
            },
        ),
    ]
