# Generated by Django 3.2.9 on 2022-04-10 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juanzeng', '0001_initial'),
        ('wupinleibie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bianhao', models.CharField(default='', max_length=50, verbose_name='编号')),
                ('biaoti', models.CharField(default='', max_length=255, verbose_name='标题')),
                ('wupin', models.CharField(default='', max_length=255, verbose_name='物品')),
                ('shuliang', models.IntegerField(default=0, verbose_name='数量')),
                ('juanzengren', models.CharField(db_column='juanzengren', default='', max_length=50, verbose_name='捐赠人')),
                ('wuliugongsi', models.CharField(default='', max_length=50, verbose_name='物流公司')),
                ('wuliudanhao', models.CharField(default='', max_length=50, verbose_name='物流单号')),
                ('beizhu', models.TextField(default='', verbose_name='备注')),
                ('juanjizhuangtai', models.CharField(choices=[('待审核', '待审核'), ('已通过', '已通过'), ('未通过', '未通过')], default='', max_length=512, verbose_name='捐寄状态')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('juanzengid', models.ForeignKey(db_column='juanzengid', default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='juanji_Juanzeng_juanzengid', to='juanzeng.juanzeng', verbose_name='捐赠id')),
                ('wupinleibie', models.ForeignKey(db_column='wupinleibie', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='juanji_Wupinleibie_wupinleibie', to='wupinleibie.wupinleibie')),
            ],
            options={
                'verbose_name': '捐寄',
                'verbose_name_plural': '捐寄',
                'db_table': 'juanji',
            },
        ),
    ]
