# Generated by Django 3.2.9 on 2022-04-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xinwenfenlei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fenleimingcheng', models.CharField(default='', max_length=50, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '新闻分类',
                'verbose_name_plural': '新闻分类',
                'db_table': 'xinwenfenlei',
            },
        ),
    ]
