# Generated by Django 3.2.9 on 2022-04-10 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wupinleibie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xuqiuxinxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xuqiubianhao', models.CharField(default='', max_length=50, verbose_name='需求编号')),
                ('biaoti', models.CharField(default='', max_length=255, verbose_name='标题')),
                ('wuzhimingcheng', models.CharField(default='', max_length=255, verbose_name='物质名称')),
                ('shuliang', models.IntegerField(default=0, verbose_name='数量')),
                ('xingming', models.CharField(default='', max_length=50, verbose_name='姓名')),
                ('shoujihao', models.CharField(default='', max_length=50, verbose_name='手机号')),
                ('lianxidizhi', models.CharField(default='', max_length=50, verbose_name='联系地址')),
                ('xuqiumiaoshu', models.TextField(default='', verbose_name='需求描述')),
                ('zhuangtai', models.CharField(choices=[('待审核', '待审核'), ('未通过', '未通过'), ('待捐赠', '待捐赠'), ('已领取', '已领取')], default='', max_length=512, verbose_name='状态')),
                ('dengjiren', models.CharField(db_column='dengjiren', default='', max_length=50, verbose_name='登记人')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('wuzhileibie', models.ForeignKey(db_column='wuzhileibie', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='xuqiuxinxi_Wupinleibie_wuzhileibie', to='wupinleibie.wupinleibie')),
            ],
            options={
                'verbose_name': '需求信息',
                'verbose_name_plural': '需求信息',
                'db_table': 'xuqiuxinxi',
            },
        ),
    ]
