# Generated by Django 3.2.9 on 2022-04-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yonghu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yonghuming', models.CharField(default='', max_length=50, verbose_name='用户名')),
                ('mima', models.CharField(default='', max_length=128, verbose_name='密码')),
                ('xingming', models.CharField(default='', max_length=50, verbose_name='姓名')),
                ('nicheng', models.CharField(default='', max_length=50, verbose_name='昵称')),
                ('xingbie', models.CharField(choices=[('男', '男'), ('女', '女')], default='', max_length=512, verbose_name='性别')),
                ('shoujihao', models.CharField(default='', max_length=50, verbose_name='手机号')),
                ('youxiang', models.CharField(default='', max_length=50, verbose_name='邮箱')),
                ('shenfenzheng', models.CharField(default='', max_length=50, verbose_name='身份证')),
                ('dizhi', models.CharField(default='', max_length=50, verbose_name='地址')),
                ('aixinjifen', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='爱心积分')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'yonghu',
            },
        ),
    ]
