# Generated by Django 3.2.9 on 2022-04-10 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shenling', '0001_initial'),
        ('juanzeng', '0001_initial'),
        ('wupinleibie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bianhao', models.CharField(default='', max_length=50, verbose_name='编号')),
                ('biaoti', models.CharField(default='', max_length=255, verbose_name='标题')),
                ('wupin', models.CharField(default='', max_length=255, verbose_name='物品')),
                ('shuliang', models.IntegerField(default=0, verbose_name='数量')),
                ('juanzengren', models.CharField(db_column='juanzengren', default='', max_length=50, verbose_name='捐赠人')),
                ('shenlingrenxingming', models.CharField(default='', max_length=50, verbose_name='申领人姓名')),
                ('shenlingrenxingbie', models.CharField(choices=[('男', '男'), ('女', '女')], default='', max_length=512, verbose_name='申领人性别')),
                ('shenlingrendianhua', models.CharField(default='', max_length=50, verbose_name='申领人电话')),
                ('shenlingrendizhi', models.CharField(default='', max_length=50, verbose_name='申领人地址')),
                ('shenqingyonghu', models.CharField(db_column='shenqingyonghu', default='', max_length=50, verbose_name='申请用户')),
                ('wuliugongsi', models.CharField(default='', max_length=50, verbose_name='物流公司')),
                ('wuliudanhao', models.CharField(default='', max_length=50, verbose_name='物流单号')),
                ('beizhu', models.TextField(default='', verbose_name='备注')),
                ('caozuoren', models.CharField(db_column='caozuoren', default='', max_length=50, verbose_name='操作人')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('juanzengid', models.ForeignKey(db_column='juanzengid', default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='paiji_Juanzeng_juanzengid', to='juanzeng.juanzeng', verbose_name='捐赠id')),
                ('shenlingid', models.ForeignKey(db_column='shenlingid', default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='paiji_Shenling_shenlingid', to='shenling.shenling', verbose_name='申领id')),
                ('wupinleibie', models.ForeignKey(db_column='wupinleibie', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paiji_Wupinleibie_wupinleibie', to='wupinleibie.wupinleibie')),
            ],
            options={
                'verbose_name': '派寄',
                'verbose_name_plural': '派寄',
                'db_table': 'paiji',
            },
        ),
    ]
