# Generated by Django 3.2.9 on 2022-04-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liuyanxinxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shouxinren', models.CharField(db_column='shouxinren', default='', max_length=50, verbose_name='收信人')),
                ('xinxineirong', models.TextField(default='', verbose_name='信息内容')),
                ('faxinren', models.CharField(db_column='faxinren', default='', max_length=50, verbose_name='发信人')),
                ('huifuneirong', models.TextField(default='', verbose_name='回复内容')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '留言信息',
                'verbose_name_plural': '留言信息',
                'db_table': 'liuyanxinxi',
            },
        ),
    ]
