# Generated by Django 3.2.9 on 2022-04-10 14:43

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xinwenfenlei', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xinwenxinxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biaoti', models.CharField(default='', max_length=255, verbose_name='标题')),
                ('tupian', common.models.MyImageField(default='', max_length=255, verbose_name='图片')),
                ('neirong', common.models.UMeditorField(default='', verbose_name='内容')),
                ('tianjiaren', models.CharField(db_column='tianjiaren', default='', max_length=50, verbose_name='添加人')),
                ('dianjilv', models.IntegerField(default=0, verbose_name='点击率')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('fenlei', models.ForeignKey(db_column='fenlei', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='xinwenxinxi_Xinwenfenlei_fenlei', to='xinwenfenlei.xinwenfenlei')),
            ],
            options={
                'verbose_name': '新闻信息',
                'verbose_name_plural': '新闻信息',
                'db_table': 'xinwenxinxi',
            },
        ),
    ]
