# Generated by Django 3.2.9 on 2022-04-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wupinleibie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leibieming', models.CharField(default='', max_length=50, verbose_name='类别名')),
            ],
            options={
                'verbose_name': '物品类别',
                'verbose_name_plural': '物品类别',
                'db_table': 'wupinleibie',
            },
        ),
    ]
