# Generated by Django 3.2.9 on 2022-04-10 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wupinleibie', '0001_initial'),
        ('xuqiuxinxi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juanzengwuzi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xuqiubianhao', models.CharField(default='', max_length=50, verbose_name='需求编号')),
                ('biaoti', models.CharField(default='', max_length=255, verbose_name='标题')),
                ('wuzhimingcheng', models.CharField(default='', max_length=255, verbose_name='物质名称')),
                ('shuliang', models.IntegerField(default=0, verbose_name='数量')),
                ('xingming', models.CharField(default='', max_length=50, verbose_name='姓名')),
                ('shoujihao', models.CharField(default='', max_length=50, verbose_name='手机号')),
                ('lianxidizhi', models.CharField(default='', max_length=50, verbose_name='联系地址')),
                ('dengjiren', models.CharField(db_column='dengjiren', default='', max_length=50, verbose_name='登记人')),
                ('juanzengwuzhi', models.CharField(default='', max_length=255, verbose_name='捐赠物质')),
                ('juanzengshuliang', models.IntegerField(default=0, verbose_name='捐赠数量')),
                ('kuaidigongsi', models.CharField(default='', max_length=50, verbose_name='快递公司')),
                ('kuaididanhao', models.CharField(default='', max_length=50, verbose_name='快递单号')),
                ('juanzengbeizhu', models.TextField(default='', verbose_name='捐赠备注')),
                ('juanzengrennicheng', models.CharField(default='', max_length=50, verbose_name='捐赠人昵称')),
                ('juanzengzhuangtai', models.CharField(choices=[('待领取', '待领取'), ('已领取', '已领取')], default='', max_length=512, verbose_name='捐赠状态')),
                ('juanzengyonghu', models.CharField(db_column='juanzengyonghu', default='', max_length=50, verbose_name='捐赠用户')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('wuzhileibie', models.ForeignKey(db_column='wuzhileibie', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='juanzengwuzi_Wupinleibie_wuzhileibie', to='wupinleibie.wupinleibie')),
                ('xuqiuxinxiid', models.ForeignKey(db_column='xuqiuxinxiid', default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='juanzengwuzi_Xuqiuxinxi_xuqiuxinxiid', to='xuqiuxinxi.xuqiuxinxi', verbose_name='需求信息id')),
            ],
            options={
                'verbose_name': '捐赠物资',
                'verbose_name_plural': '捐赠物资',
                'db_table': 'juanzengwuzi',
            },
        ),
    ]
